### ISSUE TITLE
How to tell when a device has connected to the wifi

### ISSUE THREAD

**Issue by coop** [nerves-project/nerves_interim_wifi#1]
Hi,

I am having trouble understanding the best way to know when my device has connected to the wifi. So far I have followed the README and was able to see debug output on boot. I tried getting a little fancier and made a http request after starting the wifi and my app fails to boot:

```
$ cat lib/bbq.ex
defmodule BBQ do
  use Application

  # See http://elixir-lang.org/docs/stable/elixir/Application.html
  # for more information on OTP Applications
  def start(_type, _args) do
    import Supervisor.Spec, warn: false

    opts = Application.get_env(:bbq, :wlan0)
    {:ok, _pid} = Nerves.InterimWiFi.setup("wlan0", opts)

    {:ok, %HTTPoison.Response{status_code: 200, body: body}} = HTTPoison.get("http://httparrot.herokuapp.com/get")
    # Define workers and child supervisors to be supervised
    children = [
      # worker(BBQ.Worker, [arg1, arg2, arg3]),
    ]

    # See http://elixir-lang.org/docs/stable/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: BBQ.Supervisor]
    Supervisor.start_link(children, opts)
  end
end
```

Originally I thought `Nerves.InterimWiFi.setup("wlan0", opts)` was a blocking call, turns out it is implemented with `GenEvent` (via the [nerves network interface project](https://github.com/nerves-project/nerves_network_interface)). I figure the best thing I can do is register my own handler and listen to events, e.g. `GenEvent.add_handler(Nerves.NetworkInterface.event_manager, MyEventHandler, {self, ifname})`.

Is this the recommended way to do this?

Thanks

**Comment by fhunleth** [comment]
There's a reason it's called "interim". I pulled some existing code from another project, refactored it really quickly to make it open-source-able, and then posted it. The plan was to completely rework the event system.

In answer to your question, I've been polling the IP address to tell when I'm connected. It is not the way that I'd like to do it, but it kind of works. See https://hexdocs.pm/nerves_network_interface/Nerves.NetworkInterface.html#settings/1.

**Comment by coop** [comment]
Hi @fhunleth,

Thanks for taking the time to respond. I understand that the current state of this project is "interim" but I think it would be good to have some documentation in the README how it should be consumed. I'm hoping to get back to my project on the weekend and I'll submit a PR with my working code.

Thanks for your help.

**Comment by wsmoak** [comment]
On rpi3, when I try `Nerves.NetworkInterface.settings(:wlan0)` to check whether I'm connected, I see `netif: settings requires ifname` and then a timeout and a worker gets terminated.

**Comment by mobileoverlord** [comment]
I have merged in a change which adds support for monitoring messages for the interface from`Registry`.  There is an example of how to use this to monitor for network interface changes in the README of `nerves_network_interface` It would be great if you could give this a spin and let me know how it works for you.

**Comment by GregMefford** [comment]
Going to go ahead and close this issue now since it's getting pretty stale.
Feel free to open a new issue if you run into issues with the new `Registry`-based method! 🚀

**Comment by coop** [comment]
Thanks for the hard work guys.
